/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.npc;

import java.awt.*;
import java.util.List;

/**
 *
 * @author lana
 * The class for adding new stamps to the CSV file
 */
public class AddStampDialog extends javax.swing.JDialog {
    private String selectedImagePath;
    private User user;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddStampDialog.class.getName());

    /**
     * Creates new form AddStampDialog
     */
    public AddStampDialog(Frame parent, boolean modal, User user) {
        super(parent, modal);
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        btnSave = new javax.swing.JToggleButton();
        yearField = new javax.swing.JFormattedTextField();
        categoryField = new javax.swing.JComboBox<>();
        fileField = new javax.swing.JFileChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        countryField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 650));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 36)); // NOI18N
        jLabel1.setText("Add New Stamp");

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel2.setText("Title");

        titleField.addActionListener(this::titleFieldActionPerformed);

        btnSave.setBackground(new java.awt.Color(11, 61, 145));
        btnSave.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        yearField.addActionListener(this::yearFieldActionPerformed);

        categoryField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Definitive", "Commemorative", "Used", "Mint" }));

        fileField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        fileField.setDragEnabled(true);
        fileField.setMinimumSize(new java.awt.Dimension(650, 250));
        fileField.setPreferredSize(new java.awt.Dimension(590, 250));
        fileField.addActionListener(this::fileFieldActionPerformed);

        jLabel3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel3.setText("Category");

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel4.setText("Year");

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel5.setText("Country");

        countryField.addActionListener(this::countryFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fileField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(25, 25, 25)
                                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(65, 65, 65)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(jLabel1)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fileField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed

    private void yearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearFieldActionPerformed

    private void countryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFieldActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Validate that an image is selected before processing.
        if (fileField.getSelectedFile() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an image");
            return;
        }

        saveStamp(copyImageToProject(fileField.getSelectedFile().getAbsolutePath()));
    }//GEN-LAST:event_btnSaveActionPerformed

    private void fileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileFieldActionPerformed
    private int generateNextStampId() { // Scan CSV file to find the highest ID and increments it
        int maxId = 0;

        List<String[]> rows = CsvHandler.readData("stamps.csv");

        for (String[] row : rows) {
            if (row.length == 0) continue;

            try {
                int id = Integer.parseInt(row[0]);
                if (id > maxId) {
                    maxId = id;
                }
            } catch (NumberFormatException e) {
                // Ignore broken / invalid IDs
            }
        }

        return maxId + 1;
    }
    // Copies the user-selected image into the project's directory
    private String copyImageToProject(String originalPath) {
        try {
            java.io.File srcFile = new java.io.File(originalPath);
            String imagesDir = "img"; // project folder
            java.io.File dir = new java.io.File(imagesDir);
            if (!dir.exists()) dir.mkdirs();

            String newFileName = srcFile.getName(); 
            java.io.File destFile = new java.io.File(dir, newFileName);

            java.nio.file.Files.copy(
                    srcFile.toPath(),
                    destFile.toPath(),
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING
            );

            return destFile.getPath(); // Returns the path inside the project

        } catch (Exception e) {
            e.printStackTrace();
            return originalPath; // If copy fails, returns the original path
        }
    }
    private void saveStamp(String imagePath) {

        String title = titleField.getText().trim();
        String category = (String) categoryField.getSelectedItem();
        String year = yearField.getText().trim();
        String country = countryField.getText().trim();

        if (title.isEmpty() || year.isEmpty() || country.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Fill all fields");
            return;
        }

        int id = generateNextStampId();
        String ownerEmail = user.getEmail();

        CsvHandler.ensureFileExists("stamps.csv", "ID,Title,Category,Year,Country,Image,Owner"); // если файла нет
        List<String[]> rows = CsvHandler.read("stamps.csv"); 

        // Add new row
        rows.add(new String[]{String.valueOf(id), title, category, year, country, imagePath, ownerEmail});

        // Rewrite CSV
        CsvHandler.writeAll("stamps.csv", rows);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSave;
    private javax.swing.JComboBox<String> categoryField;
    private javax.swing.JTextField countryField;
    private javax.swing.JFileChooser fileField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField titleField;
    private javax.swing.JFormattedTextField yearField;
    // End of variables declaration//GEN-END:variables
}
