/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.npc;

/**
 *
 * @author lana
 */
public class EditUserDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditUserDialog.class.getName());
    private User currentUser;
    private User editedUser;
    /**
     * Creates new form EditUserDialog
     */
    public EditUserDialog(java.awt.Frame parent, boolean modal, User currentUser, User editedUser) {
        super(parent, modal);
        initComponents();
        
        this.currentUser = currentUser;
        this.editedUser = editedUser;
        
        fillFields();
        applyPermissions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        nameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        roleField = new javax.swing.JComboBox<>();
        roleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit User");

        passwordField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N

        nameField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N

        surnameField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N

        saveBtn.setBackground(new java.awt.Color(11, 61, 145));
        saveBtn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        passwordLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        passwordLabel.setText("Password");

        nameLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        nameLabel.setText("Name");

        surnameLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        surnameLabel.setText("Surname");

        roleField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        roleField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        roleField.addActionListener(this::roleFieldActionPerformed);

        roleLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        roleLabel.setText("Role");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLabel)
                    .addComponent(nameLabel)
                    .addComponent(surnameLabel)
                    .addComponent(roleLabel))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameField)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roleField, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(saveBtn)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surnameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleLabel))
                .addGap(18, 18, 18)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        passwordField.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if (currentUser.isAdmin()) {
            editedUser.setName(nameField.getText().trim());
            editedUser.setSurname(surnameField.getText().trim());
            String selected = roleField.getSelectedItem().toString();
            int value = selected.equals("Admin") ? 1 : 0;
            editedUser.setRole(value);
        }

        String newPassword = new String(passwordField.getPassword()).trim();
        if (newPassword.isEmpty()) {
            newPassword = null;
        }

        UserController.updateUser(editedUser, newPassword);
        dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void roleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleFieldActionPerformed
    private void fillFields() {
        nameField.setText(editedUser.getName());
        surnameField.setText(editedUser.getSurname());
        passwordField.setText(""); // password never display
    }
    private void applyPermissions() {
        if (currentUser.isAdmin()) {
            nameField.setEnabled(true);
            surnameField.setEnabled(true);
            roleLabel.setVisible(true);
            roleField.setVisible(true);
            
            roleField.setSelectedIndex(editedUser.isAdmin() ? 1 : 0);
        } else {
            nameField.setEnabled(false);
            surnameField.setEnabled(false);
            roleLabel.setVisible(false);
            roleField.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox<String> roleField;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField surnameField;
    private javax.swing.JLabel surnameLabel;
    // End of variables declaration//GEN-END:variables
}
