/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.npc;

import java.awt.EventQueue;
import java.awt.Frame;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.util.List;

/**
 *
 * @author lana
 * A class for editing existing stamp record
 * Loading data from CSV, displaying the current stamp's data
 * Saving stamp's data to CSV file after modification
 */
public class EditStampDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditStampDialog.class.getName());
    private User user;
    private String stampId;

    /**
     * Creates new form EditStampDialog
     * Basic constructor
     */
    public EditStampDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    // Primary constructor for editing a specific stamp
    public EditStampDialog(Frame parent, User user, String stampId) {
        super(parent, true);
        this.user = user;
        this.stampId = stampId;

        initComponents();
        loadStampData();   // Data Loading
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleField = new javax.swing.JTextField();
        countryField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        categoryField = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        stampImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        titleField.setVerifyInputWhenFocusTarget(false);

        countryField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N

        yearField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N

        titleLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        titleLabel.setText("Title");

        categoryLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        categoryLabel.setText("Category");

        yearLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        yearLabel.setText("Year");

        countryLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        countryLabel.setText("Country");
        countryLabel.setToolTipText("");

        categoryField.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        categoryField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Definitive", "Commemorative", "Used", "Mint" }));
        categoryField.setToolTipText("");
        categoryField.setVerifyInputWhenFocusTarget(false);

        saveBtn.setBackground(new java.awt.Color(11, 61, 145));
        saveBtn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        stampImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stampImageLabel.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(yearLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(categoryLabel)
                                        .addComponent(countryLabel))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(titleLabel)
                                    .addGap(75, 75, 75)
                                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(stampImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(stampImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleField, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(titleLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLabel)
                    .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryLabel))
                .addGap(18, 18, 18)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // Reads the Stamps CSV file, updates the specific row
        List<String[]> rows = CsvHandler.read("stamps.csv");

        for (int i = 1; i < rows.size(); i++) { // Start from 1 row, skip header
            String[] d = rows.get(i);

            if (d.length < 7) continue;

            if (d[0].equals(stampId)) {
                rows.set(i, new String[]{
                    d[0],                                   // ID
                    titleField.getText().trim(),
                    categoryField.getSelectedItem().toString(),
                    yearField.getText().trim(),
                    countryField.getText().trim(),
                    d[5],                                   // Image
                    d[6]                                    // Owner
                });
                break;
            }
        }

        CsvHandler.writeAll("stamps.csv", rows);
        dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditStampDialog dialog = new EditStampDialog(new JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Search the CSV file for specific row by stamp ID and display form field with stamp's data
    private void loadStampData() {
        List<String[]> rows = CsvHandler.readData("stamps.csv");

        for (String[] d : rows) {
            if (d.length < 7) continue;

            if (d[0].equals(stampId)) {
                titleField.setText(d[1]);
                categoryField.setSelectedItem(d[2]);
                yearField.setText(d[3]);
                countryField.setText(d[4]);

                File imgFile = new File(d[5]);
                if (imgFile.exists()) {
                    Image img = new ImageIcon(d[5])
                            .getImage()
                            .getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                    stampImageLabel.setIcon(new ImageIcon(img));
                } else {
                    stampImageLabel.setIcon(null);
                }
                break;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoryField;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField countryField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel stampImageLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField yearField;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
