/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.npc;

import javax.swing.SwingUtilities;

/**
 *
 * @author lana
 */
public class MyAccountPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    /**
     * Creates new form MyAccountPanel
     */
    public MyAccountPanel(MainFrame mainFrame, User user) {
        this.mainFrame = mainFrame;
        initComponents();

        emailLabel.setText("Email: " + user.email);
        nameLabel.setText("Name: " + user.name);
        surnameLabel.setText("Surname: " + user.surname);
        roleLabel.setText(user.role == 1 ? "Role: Admin" : "Role: User");
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        changePasswordBtn = new javax.swing.JButton();

        nameLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        nameLabel.setText("Name");

        emailLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        emailLabel.setText("Email");

        surnameLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        surnameLabel.setText("Surname");

        roleLabel.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        roleLabel.setText("Role");

        changePasswordBtn.setBackground(new java.awt.Color(11, 61, 145));
        changePasswordBtn.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        changePasswordBtn.setForeground(new java.awt.Color(255, 255, 255));
        changePasswordBtn.setText("Change Password");
        changePasswordBtn.addActionListener(this::changePasswordBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roleLabel)
                            .addComponent(surnameLabel)
                            .addComponent(nameLabel)
                            .addComponent(emailLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(changePasswordBtn)))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emailLabel, nameLabel, roleLabel, surnameLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(surnameLabel)
                .addGap(18, 18, 18)
                .addComponent(emailLabel)
                .addGap(18, 18, 18)
                .addComponent(roleLabel)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordBtnActionPerformed
        User currentUser = mainFrame.getCurrentUser();
        EditUserDialog dialog = new EditUserDialog(
            (java.awt.Frame) SwingUtilities.getWindowAncestor(this), 
            true, 
            currentUser, 
            currentUser 
        );
        dialog.setVisible(true);
    }//GEN-LAST:event_changePasswordBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel surnameLabel;
    // End of variables declaration//GEN-END:variables
}
