/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.npc;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lana
 */
public class TopMenuPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;
    private JPanel menuPanel;
    /**
     * Creates new form TopMenuPanel
     */
    public TopMenuPanel(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        updateMenu(null);
    }
    public void updateMenu(User user) {

        btnLogin.setVisible(false);
        btnRegister.setVisible(false);
        btnMyAccount.setVisible(false);
        btnMyStamps.setVisible(false);
        btnWishList.setVisible(false);
        btnLogout.setVisible(false);
        btnAllStamps.setVisible(false);
        btnAllUsers.setVisible(false);

        if (user == null) {
            // User is not authenticated
            btnAllStamps.setVisible(true);
            btnLogin.setVisible(true);
            btnRegister.setVisible(true);
        } else if (user.isAdmin()) {
            // Admin user
            btnAllUsers.setVisible(true);
            btnAllStamps.setVisible(true);
            btnMyAccount.setVisible(true);
            btnMyStamps.setVisible(true);
            btnWishList.setVisible(true);
            btnLogout.setVisible(true);
        } else {
            // Regular user
            btnAllStamps.setVisible(true);
            btnMyAccount.setVisible(true);
            btnMyStamps.setVisible(true);
            btnWishList.setVisible(true);
            btnLogout.setVisible(true);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAllStamps = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnMyAccount = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnMyStamps = new javax.swing.JButton();
        btnWishList = new javax.swing.JButton();
        btnAllUsers = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 100));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jLabel1.setText("NPC");

        btnAllStamps.setBackground(new java.awt.Color(11, 61, 145));
        btnAllStamps.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnAllStamps.setForeground(new java.awt.Color(255, 255, 255));
        btnAllStamps.setText("All Stamps");
        btnAllStamps.addActionListener(this::btnAllStampsActionPerformed);

        btnRegister.setBackground(new java.awt.Color(11, 61, 145));
        btnRegister.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(this::btnRegisterActionPerformed);

        btnLogin.setBackground(new java.awt.Color(11, 61, 145));
        btnLogin.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        btnMyAccount.setBackground(new java.awt.Color(11, 61, 145));
        btnMyAccount.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnMyAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnMyAccount.setText("My Account");
        btnMyAccount.addActionListener(this::btnMyAccountActionPerformed);

        btnLogout.setBackground(new java.awt.Color(11, 61, 145));
        btnLogout.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnMyStamps.setBackground(new java.awt.Color(11, 61, 145));
        btnMyStamps.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnMyStamps.setForeground(new java.awt.Color(255, 255, 255));
        btnMyStamps.setText("My Stamps");
        btnMyStamps.addActionListener(this::btnMyStampsActionPerformed);

        btnWishList.setBackground(new java.awt.Color(11, 61, 145));
        btnWishList.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnWishList.setForeground(new java.awt.Color(255, 255, 255));
        btnWishList.setText("My Wish List");
        btnWishList.setActionCommand("My Wishlist");
        btnWishList.addActionListener(this::btnWishListActionPerformed);

        btnAllUsers.setBackground(new java.awt.Color(11, 61, 145));
        btnAllUsers.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        btnAllUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnAllUsers.setText("All Users");
        btnAllUsers.addActionListener(this::btnAllUsersActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(btnAllUsers)
                .addGap(18, 18, 18)
                .addComponent(btnAllStamps)
                .addGap(18, 18, 18)
                .addComponent(btnMyAccount)
                .addGap(18, 18, 18)
                .addComponent(btnMyStamps)
                .addGap(18, 18, 18)
                .addComponent(btnWishList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAllStamps, btnLogin, btnRegister});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWishList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMyStamps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMyAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAllUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAllStamps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllStampsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllStampsActionPerformed
        // TODO add your handling code here:
        User user = mainFrame.getCurrentUser();
        mainFrame.showPanel(new AllStamps(user));
    }//GEN-LAST:event_btnAllStampsActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:                                           
        mainFrame.showPanel(new RegisterPanel());
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        mainFrame.showPanel(new LoginPanel(mainFrame));
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnMyStampsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyStampsActionPerformed
        // TODO add your handling code here:
        User user = mainFrame.getCurrentUser();

        if (user != null) {
            mainFrame.showPanel(new UserStamps(user));
        }else{
            JOptionPane.showMessageDialog(this, "Please login first");
            return;
        }
    }//GEN-LAST:event_btnMyStampsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        mainFrame.logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnWishListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWishListActionPerformed
        // TODO add your handling code here:
        User user = mainFrame.getCurrentUser();
        mainFrame.showPanel(new WishlistStamps(user));
    }//GEN-LAST:event_btnWishListActionPerformed

    private void btnMyAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyAccountActionPerformed
        // TODO add your handling code here:
        User user = mainFrame.getCurrentUser();
        mainFrame.showPanel(new MyAccountPanel(mainFrame, user));
    }//GEN-LAST:event_btnMyAccountActionPerformed

    private void btnAllUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllUsersActionPerformed
        // TODO add your handling code here:
        User user = mainFrame.getCurrentUser();
        mainFrame.showPanel(new AdminUsersPanel(mainFrame, user));
    }//GEN-LAST:event_btnAllUsersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllStamps;
    private javax.swing.JButton btnAllUsers;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyAccount;
    private javax.swing.JButton btnMyStamps;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnWishList;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
